version: '3.8'

services:
  esxi-vm-launcher:
    build: .
    container_name: esxi-vm-launcher
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=1698118fc34eefc05338dcbae91ae3ffdf1a75b35e8de5b51da35278aae29278
      - TZ=Europe/Berlin
    networks:
      - esxi-network

networks:
  esxi-network:
    driver: bridge